[package]
name = "hermes"
version = "0.1.0"
authors = ["emil"]

[dependencies]
rand = "0.4"
chrono = "0.4"
time ="*"
#tiny_http = "*"
#rustc-serialize = "*"
ascii = "*"
handlebars = "*"
regex = "*"
getopts = "*"
clippy = { version = "*", optional = true }
